### ISSUE TITLE
Upgrade to Nexus 3.21.2 - Critical security vulnerability in all versions of NXRM 3 <= 3.21.1.

### ISSUE THREAD

**Issue by pascal-hofmann** [travelaudience/docker-nexus#35]
A critical security vulnerability has been found in all versions of NXRM 3 up to and including 3.21.1.

See https://help.sonatype.com/repomanager3/release-notes/2020-release-notes#id-2020ReleaseNotes-RepositoryManager3.21.2

**Comment by maaaikoool** [comment]
Hi! Many thanks for the fix! However it has not been pushed to the registry https://quay.io/repository/travelaudience/docker-nexus?tab=tags

**Comment by psychopenguin** [comment]
Hi @maaaikoool -  I forgot to tag the release. It's fixed now. :)

**Comment by maaaikoool** [comment]
Many thanks!
