### ISSUE TITLE
Why such Docker?

### ISSUE THREAD

**Issue by gbonnefille** [travelaudience/docker-nexus#39]
Hi,

Please, can you elaborate, in the README for example, on the difference with the official Docker for Nexus?

https://github.com/sonatype/docker-nexus3

As a simple user, it is quite difficult to decide which solution should be used.

**Comment by jeff-knurek** [comment]
@gbonnefille that's a good point. The documentation on `why` isn't really existing. But it's a pretty important reason. 

The situation is that if you have Nexus running in Kubernetes, if you want to restore from a backup, based on the documentation https://help.sonatype.com/repomanager3/backup-and-restore/restore-exported-databases, the first step is to stop Nexus. 
But stopping the service stops the official docker image, which kills the pod. Meaning, you can't restore from backup files with the official docker image.

There is a little bit of documentation regarding restoring from backup, and why we made our own image: 
https://github.com/travelaudience/kubernetes-nexus#restore
> At this point, Nexus is stopped but the container is still running, giving us a chance to perform the restore procedure. 

But I agree, this should be clarified.

**Comment by gbonnefille** [comment]
OK, thanks for clarification. It is effectively a good motivation.

**Comment by gbonnefille** [comment]
Related to that, I have the feeling that Nexus is not really *cloud-ready* at least in the meaning of *cloud* seen by K8S.
And clearly, such evolved situation are not handled by raw/simple K8S objects.
Perhaps this is the goal of K8S [*operators*](https://coreos.com/operators/) (not investigated yet).
