### ISSUE TITLE
please release new version to quay.io

### ISSUE THREAD

**Issue by azhurbilo** [travelaudience/docker-nexus#65]
```
docker pull quay.io/travelaudience/docker-nexus:3.30.1
Error response from daemon: manifest for quay.io/travelaudience/docker-nexus:3.30.1 not found: manifest unknown: manifest unknown
```

latest available 3.31.1 (official)

latest available in quay.io is 3.29.2 (6 month ago)

it's important as 3.29.2 contains critical vulnerabilities

**Comment by cmoroianu1** [comment]
just released: https://github.com/travelaudience/docker-nexus/releases/tag/3.31.0-01

Also feel free to open PRs in the future, that will speed-up the releases.

**Comment by azhurbilo** [comment]
@cmoroianu1 could you check that image will be available in quay.io ?

thnx a lot for your super fast reaction 👍 

![image](https://user-images.githubusercontent.com/6387460/124266274-6d69b980-db3f-11eb-9c73-8674ab904199.png)

**Comment by azhurbilo** [comment]
@cmoroianu1 could you check? image still is not available
