### ISSUE TITLE
[feature request] check success status when new release version commited to repo

### ISSUE THREAD

**Issue by azhurbilo** [travelaudience/docker-nexus#66]
see that such issue (fail publish to Quay because of docker rate limits) reproduced several times

https://github.com/travelaudience/docker-nexus/issues/60#issuecomment-757831849
https://github.com/travelaudience/docker-nexus/issues/65#issuecomment-872919174

https://quay.io/repository/travelaudience/docker-nexus?tab=info

may be it's possible to automate somehow or control status of publishing?

![image](https://user-images.githubusercontent.com/6387460/125280857-37d28680-e31e-11eb-91f0-5e557c295844.png)

**Comment by cmoroianu1** [comment]
closing. will keep an eye on the status of the build when publishing releases.
