### ISSUE TITLE
Latest Images Missing

### ISSUE THREAD

**Issue by mohammadsrahman** [travelaudience/docker-nexus#67]
The latest images after 3.29.2 are missing from https://quay.io/repository/travelaudience/docker-nexus?tag=3.13.0_alpine_3.8.1&tab=tags . Please can you publish these? I was trying to upgrade to 3.30.1 but couldn’t find the images anywhere.

**Comment by cmoroianu1** [comment]
closing. old issue. newer images have been posted.
