### ISSUE TITLE
Image version 3.37.1-01 is missing in quay

### ISSUE THREAD

**Issue by pavel-kurnosov** [travelaudience/docker-nexus#72]
You released an important upgrade a few days ago, but I could not find it in quay to upgrade. Could you release it to https://quay.io/repository/travelaudience/docker-nexus?

**Comment by cmoroianu1** [comment]
Hi Pavel, thanks for reaching out. A new release has been created, once the build finishes, the image will be available. Right now it looks quay has some issues.

**Comment by pavel-kurnosov** [comment]
Yea looks like the build is stuck.
