### ISSUE TITLE
Nexus slow start large cache repository

### ISSUE THREAD

**Issue by wjeanneau** [travelaudience/docker-nexus#9]
https://github.com/travelaudience/docker-nexus/blob/5fdd774e780f93b3bf0499bb312706268363e6a2/run#L4

Hi,

Could you explain why we are doing a change owner here on the folder /nexus-data ?
We have more than 15K packages in a cache repo, and we need almost 20 minutes to start the container/service. 

Thank you.

**Comment by pires** [comment]
In order to make sure the permissions are set properly.
